"""Building a target's locators from the element a use put it to: the
compiler's half of ADR-0025's locator grammar (DATA_MODEL §7, Locators;
ADR-0025's 2026-10-02 amendment, "generating locators").

The caller says what the element is for and what each use is; this module
finds the locators. Every locator it returns was resolved alone, on the live
page, to the element the use put to it. That is judged through Playwright's
utility world, which the page's scripts can't reach, so a page can make the
generator build fewer or odder locators, but never one that finds another
element."""

import json
import re
import secrets
import typing
from collections.abc import Awaitable, Callable, Iterator
from dataclasses import dataclass, field
from typing import Annotated, Literal, TypedDict

from aqa_core.compiled import (
    AriaRole,
    ByCss,
    ByLabel,
    ByPlaceholder,
    ByRole,
    ByTestId,
    Locator,
    Target,
)
from aqa_core.text import normalize
from playwright.async_api import ElementHandle, Error, Page
from pydantic import Field, StringConstraints, TypeAdapter, ValidationError

from aqa_runner.browser_session import ELEMENT_REF, LINE, BrowserSession
from aqa_runner.locators import Resolved, resolve

# The key of an element's line in a snapshot, up to its ref: its role, its
# name as JSON if it has one, then attributes such as [level=1].
_DESCRIBED = re.compile(
    r'(?P<role>[a-z]+)(?: (?P<name>"(?:[^"\\\n]|\\.)*"))?(?: \[[^\]\n]*\])* '
)

# The roles whose accessible name a person reads as the control's label. Any
# other role is a container or a landmark, whose name, if it has one, is the
# text inside it, so a name never finds one (ADR-0025).
_NAMED_ROLES = frozenset(
    {
        "button",
        "checkbox",
        "combobox",
        "link",
        "menuitem",
        "menuitemcheckbox",
        "menuitemradio",
        "option",
        "radio",
        "searchbox",
        "slider",
        "spinbutton",
        "switch",
        "tab",
        "textbox",
        "treeitem",
    }
)

# The roles a role locator can take: Playwright's, less the ones that say an
# element has no role of its own.
_ROLES = frozenset(typing.get_args(AriaRole)) - {"generic", "none", "presentation"}

# A class, id, tag or attribute value that a css locator may use: one CSS
# identifier that needs no escaping, so it can't carry >>, a quote, a colon or
# a character Playwright trims.
_TOKEN = re.compile(r"[A-Za-z][A-Za-z0-9_-]*")
# Generated by a tool, not written by a person: CSS-in-JS prefixes and
# Angular's runtime classes (ng-untouched, ng-star-inserted).
_GENERATED_PREFIX = re.compile(r"(?:css|sc|jsx|emotion|svelte|ng)-")
# Classes that say what state an element is in, not what it is.
_STATE_CLASSES = frozenset(
    {
        "active",
        "checked",
        "collapsed",
        "disabled",
        "expanded",
        "focus",
        "hidden",
        "hover",
        "open",
        "selected",
        "show",
    }
)

# What one element may cost, whatever the page gives: the nearest ancestors
# and the first stable classes of each node that are tried, and the page
# round trips in all.
_ANCESTORS_TRIED = 16
_CLASSES_TRIED = 16
_ROUND_TRIPS = 400

# The attribute the used element carries, with a random value, while its
# candidates are resolved.
_MARK = "data-aqa-generating"

# What a use puts a target to (aqa_runner.locators.Use).
type GeneratedUse = Literal["action"]

# The meaning of the one-locator targets each candidate is resolved as.
_CANDIDATE_MEANING = "the element a use put a target to"

# The element's facts and its nearest ancestors', up to but not including
# <body>. Read in the page's own world, so they are the page's word: every
# candidate built from them is resolved before it is kept.
_FACTS = f"""(element) => {{
    const facts = (node) => ({{
        tag: node.localName,
        id: node.getAttribute("id"),
        classes: [...node.classList],
        name: node.getAttribute("name"),
        type: node.getAttribute("type"),
    }});
    const ancestors = [];
    for (let node = element.parentElement; node; node = node.parentElement) {{
        if (node === document.body || node === document.documentElement) break;
        if (ancestors.length === {_ANCESTORS_TRIED}) break;
        ancestors.push(facts(node));
    }}
    return {{
        ...facts(element),
        placeholder: element.getAttribute("placeholder"),
        testid: element.getAttribute("data-testid"),
        labels: element.labels ? [...element.labels].map((label) => label.innerText) : [],
        ancestors,
    }};
}}"""

# The facts' shape, checked strictly, with bounded sizes: they come from the
# page's own world.
_Token = Annotated[str, StringConstraints(strict=True, max_length=256)]
_Text = Annotated[str, StringConstraints(strict=True, max_length=1024)]


class _Node(TypedDict):
    tag: _Token
    id: _Text | None
    classes: Annotated[list[_Text], Field(max_length=256)]
    name: _Text | None
    type: _Text | None


class _Element(_Node):
    placeholder: _Text | None
    testid: _Text | None
    labels: Annotated[list[_Text], Field(max_length=64)]
    ancestors: Annotated[list[_Node], Field(max_length=_ANCESTORS_TRIED)]


_ELEMENT = TypeAdapter(_Element)


@dataclass(frozen=True)
class Seen:
    """The element a use put a target to, and the role and accessible name
    that its ref's line in the session's snapshot gives it. An element the
    snapshot gives no ref of its own, such as text inside a button, has
    neither."""

    element: ElementHandle
    role: str | None = None
    name: str | None = None


class LocatorError(LookupError):
    """No locator of the grammar finds the element, alone, for the use."""


def _name_as_written(name: str | None) -> str | None:
    """A snapshot name, decoded from JSON, or None for one that holds a lone
    surrogate, which no locator can carry."""
    if name is None:
        return None
    decoded: str = json.loads(name)
    try:
        decoded.encode()
    except UnicodeEncodeError:
        return None
    return decoded


def snapshot_elements(snapshot: str) -> dict[str, tuple[str, str | None]]:
    """Each element ref in a session's snapshot, in page order, with the role
    and the name, as written, that the snapshot gives the element."""
    elements: dict[str, tuple[str, str | None]] = {}
    for line in LINE.finditer(snapshot):
        key = line["key"]
        if key.startswith("'"):
            key = key[1:-1].replace("''", "'")
        own = ELEMENT_REF.search(key) if line["head"] else None
        described = None if own is None else _DESCRIBED.fullmatch(key, 0, own.start())
        if own is None or described is None:
            continue
        elements[own[1]] = (described["role"], _name_as_written(described["name"]))
    return elements


async def seen_element(session: BrowserSession, snapshot: str, ref: str) -> Seen:
    """The element `ref` names in the session's current snapshot, whose text
    is `snapshot`, with the role and name the snapshot gives it."""
    element = await session.locate(ref)
    role, name = snapshot_elements(snapshot).get(ref, (None, None))
    return Seen(element, role, name)


def _stable(token: str | None) -> bool:
    """Whether a css locator may use `token`: one plain identifier, not
    generated by a tool and not a state. A generated one has a prefix such as
    `css-`, or a part of five or more characters mixing letters and digits,
    such as the hash in `Button_root__x7Kd2`."""
    if token is None or not _TOKEN.fullmatch(token):
        return False
    if _GENERATED_PREFIX.match(token) or token in _STATE_CLASSES:
        return False
    return not any(
        len(part) >= 5 and re.search(r"[0-9]", part) and re.search(r"[A-Za-z]", part)
        for part in re.split(r"[-_]", token)
    )


def _structures(node: _Node) -> list[str]:
    """CSS for `node` alone, most particular first: its custom-element tag, a
    stable attribute, each of its first stable classes, then its tag. Never
    positional."""
    tag = node["tag"]
    if not _stable(tag):
        return []
    parts = [tag] if "-" in tag else []
    for attribute, value in (("name", node["name"]), ("type", node["type"])):
        if _stable(value):
            parts.append(f"{tag}[{attribute}={value}]")
    classes = [name for name in node["classes"] if _stable(name)]
    parts.extend(f"{tag}.{name}" for name in classes[:_CLASSES_TRIED])
    parts.append(tag)
    return list(dict.fromkeys(parts))


def _scopes(element: _Element) -> list[str]:
    """CSS for each ancestor that could pick out one place on the page,
    nearest first: its stable id, its custom-element tag, or its tag with a
    stable attribute or one stable class. Never <html> or <body>, which every
    page has."""
    scopes: list[str] = []
    for node in element["ancestors"]:
        ids = [f"#{node['id']}"] if _stable(node["id"]) else []
        # A bare tag names every element of its kind, unless it is a custom
        # element's.
        structures = [
            each for each in _structures(node) if each != node["tag"] or "-" in each
        ]
        scopes.extend(ids + structures)
    return list(dict.fromkeys(scopes))


def _structural(element: _Element) -> Iterator[ByCss]:
    """Structural locators for the element, each alone and then under its
    nearest custom-element ancestor, such as `app-favorite-button button`."""
    custom = next(
        (
            node["tag"]
            for node in element["ancestors"]
            if "-" in node["tag"] and _stable(node["tag"])
        ),
        None,
    )
    for structure in _structures(element):
        yield ByCss(css=structure)
        if custom is not None:
            yield ByCss(css=f"{custom} {structure}")


async def _unless_the_page_breaks(page: Page, check: Awaitable[bool]) -> bool:
    """`check`'s answer, or no when the page breaks it: Playwright's general
    error type, raised here when the page navigates away or drops an element
    mid-check, which is the page's doing. A closed page raises."""
    try:
        return await check
    except Error:
        if page.is_closed():
            raise
        return False


async def _carries_only(page: Page, element: ElementHandle, mark: str) -> bool:
    """Whether `element` carries `mark` and nothing else on the page does,
    read through Playwright's utility world, where the page's scripts can't
    reach: `get_attribute` and a css count."""
    if await element.get_attribute(_MARK) != mark:
        return False
    return await page.locator(f"css=[{_MARK}='{mark}']").count() == 1


@dataclass
class _Trial:
    """Resolving candidates for one use of the element, within a budget of
    page round trips. The element carries `mark` meanwhile."""

    page: Page
    use: GeneratedUse
    mark: str
    round_trips: int = _ROUND_TRIPS
    # How many elements on the page each scope finds, counted once.
    counted: dict[str, bool] = field(default_factory=dict)

    def _spend(self) -> None:
        if self.round_trips == 0:
            raise LocatorError(
                f"no locator found the element within {_ROUND_TRIPS} tries"
            )
        self.round_trips -= 1

    async def _found(self, locator: Locator) -> bool:
        target = Target(semantic=_CANDIDATE_MEANING, locators=(locator,))
        found = await resolve(self.page, target, self.use)
        if not isinstance(found, Resolved):
            return False
        try:
            return await _carries_only(self.page, found.element, self.mark)
        finally:
            await found.element.dispose()

    async def finds(self, locator: Locator) -> bool:
        """Whether `locator`, alone, resolves for the use to the marked
        element."""
        self._spend()
        return await _unless_the_page_breaks(self.page, self._found(locator))

    async def _count_is_one(self, scope: str) -> bool:
        return await self.page.locator(f"css={scope}").count() == 1

    async def unique(self, scope: str) -> bool:
        """Whether `scope` finds one element on the page, counted once."""
        if scope not in self.counted:
            self._spend()
            self.counted[scope] = await _unless_the_page_breaks(
                self.page, self._count_is_one(scope)
            )
        return self.counted[scope]

    async def scoped_as_needed(
        self, locator: Locator, scopes: list[str]
    ) -> Locator | None:
        """`locator` if it finds the element alone, else `locator` scoped
        under the nearest scope, unique on the page, that makes it find the
        element, else None."""
        if await self.finds(locator):
            return locator
        for scope in scopes:
            if not await self.unique(scope):
                continue
            scoped = locator.model_copy(update={"scope": ByCss(css=scope)})
            if await self.finds(scoped):
                return scoped
        return None


async def _facts(page: Page, element: ElementHandle) -> _Element:
    """The element's facts, as the page gives them. A page that breaks the
    reading or gives them in a form no element has gets no locator."""
    try:
        return _ELEMENT.validate_python(await element.evaluate(_FACTS), strict=True)
    except Error:
        # Playwright's general error type: here the element left the page or
        # the page's own scripts broke the reading. A closed page is not.
        if page.is_closed():
            raise
        raise LocatorError(
            "the element couldn't be read: it left the page, or the page's "
            "scripts broke the reading"
        ) from None
    except ValidationError:
        raise LocatorError("the page described the element as no element is") from None


async def _set_mark(element: ElementHandle, mark: str) -> bool:
    # The mark is hex, so it is written into the function rather than passed
    # beside the element: the page's own world spreads arguments with an
    # iterator the page can rewrite.
    await element.evaluate(f"(element) => element.setAttribute('{_MARK}', '{mark}')")
    return True


async def _marked(page: Page, element: ElementHandle) -> str:
    """Mark the element, in the page's own world, with a fresh random value,
    and return the value once Playwright's utility world reads it on the
    element and on nothing else."""
    mark = secrets.token_hex(16)
    set_mark = await _unless_the_page_breaks(page, _set_mark(element, mark))
    if not set_mark or not await _unless_the_page_breaks(
        page, _carries_only(page, element, mark)
    ):
        raise LocatorError("the page kept the mark off the element, or copied it")
    return mark


async def _remove_mark(element: ElementHandle) -> bool:
    await element.evaluate(f"(element) => element.removeAttribute('{_MARK}')")
    return True


def _action_kinds(used: Seen, element: _Element) -> list[list[Locator]]:
    """The grammar's kinds for an action, in its order, each with its
    candidates in order: role and name, label, placeholder, test ID, stable
    id, then structure (ADR-0025)."""
    role = used.role if used.role in _ROLES else None
    name = normalize(used.name or "") if role in _NAMED_ROLES else ""
    labels = [normalize(label) for label in element["labels"]]
    placeholder = (element["placeholder"] or "").strip()
    return [
        [ByRole.model_validate({"role": role, "name": name})] if name else [],
        [ByLabel(label=label) for label in labels if label],
        [ByPlaceholder(placeholder=placeholder)] if placeholder else [],
        [ByTestId(testid=element["testid"])] if element["testid"] else [],
        [ByCss(css=f"#{element['id']}")] if _stable(element["id"]) else [],
        list(_structural(element)),
    ]


async def _generate(
    page: Page,
    used: Seen,
    use: GeneratedUse,
    kinds_of: Callable[[_Element], list[list[Locator]]],
) -> tuple[Locator, ...]:
    """The first candidate of each kind that finds the element for `use`,
    in order. Raises `LocatorError` when none does."""
    element = await _facts(page, used.element)
    mark = await _marked(page, used.element)
    found: list[Locator] = []
    try:
        trial = _Trial(page, use, mark)
        scopes = _scopes(element)
        for kind in kinds_of(element):
            for candidate in kind:
                working = await trial.scoped_as_needed(candidate, scopes)
                if working is not None:
                    found.append(working)
                    break
    finally:
        # A page that keeps the mark keeps an attribute on the element it
        # already gave; the locators were judged before.
        await _unless_the_page_breaks(page, _remove_mark(used.element))
    if not found:
        what = f"the {element['tag']} element" if _stable(element["tag"]) else "it"
        raise LocatorError(f"no locator of the grammar finds {what} alone for an {use}")
    return tuple(found)


async def generate_for_action(page: Page, used: Seen) -> tuple[Locator, ...]:
    """An action target's locators: one of each kind that finds the element
    `used`, in the grammar's order, each resolved alone, as an action, to
    that element on the page as it is now. Raises `LocatorError` when no
    locator does."""
    return await _generate(
        page, used, "action", lambda element: _action_kinds(used, element)
    )
