"""Building a target's locators from the element a use put it to: the
compiler's half of ADR-0025's locator grammar (DATA_MODEL §7, Locators;
ADR-0025's 2026-10-02 amendment, "generating locators").

The caller says what the element is for and what each use is; this module
finds the locators. Every locator it returns was resolved alone, on the live
page, to the element the use put to it, so the page can make it build fewer
or odder locators, but never one that finds another element."""

import json
import re
import typing
from collections.abc import Iterator
from dataclasses import dataclass
from typing import Literal, TypedDict, cast

from aqa_core.compiled import (
    AriaRole,
    ByCss,
    ByLabel,
    ByPlaceholder,
    ByRole,
    ByTestId,
    Locator,
    Target,
)
from aqa_core.text import normalize
from playwright.async_api import ElementHandle, Page

from aqa_runner.browser_session import ELEMENT_REF, LINE, BrowserSession
from aqa_runner.locators import Resolved, resolve

# The key of an element's line in a snapshot, up to its ref: its role, its
# name as JSON if it has one, then attributes such as [level=1].
_DESCRIBED = re.compile(
    r'(?P<role>[a-z]+)(?: (?P<name>"(?:[^"\\\n]|\\.)*"))?(?: \[[^\]\n]*\])* '
)

# The roles whose accessible name a person reads as the control's label. Any
# other role is a container or a landmark, whose name, if it has one, is the
# text inside it, so a name never finds one (ADR-0025).
_NAMED_ROLES = frozenset(
    {
        "button",
        "checkbox",
        "combobox",
        "link",
        "menuitem",
        "menuitemcheckbox",
        "menuitemradio",
        "option",
        "radio",
        "searchbox",
        "slider",
        "spinbutton",
        "switch",
        "tab",
        "textbox",
        "treeitem",
    }
)

# The roles a role locator can take: Playwright's, less the ones that say an
# element has no role of its own.
_ROLES = frozenset(typing.get_args(AriaRole)) - {"generic", "none", "presentation"}

# A class, id, tag or attribute value that a css locator may use: one CSS
# identifier that needs no escaping, so it can't carry >>, a quote or a colon.
_TOKEN = re.compile(r"[A-Za-z][A-Za-z0-9_-]*")
# Generated by a tool, not written by a person: CSS-in-JS prefixes and
# Angular's runtime classes (ng-untouched, ng-star-inserted).
_GENERATED_PREFIX = re.compile(r"(?:css|sc|jsx|emotion|svelte|ng)-")
# Classes that say what state an element is in, not what it is.
_STATE_CLASSES = frozenset(
    {
        "active",
        "checked",
        "collapsed",
        "disabled",
        "expanded",
        "focus",
        "hidden",
        "hover",
        "open",
        "selected",
        "show",
    }
)

# What a use puts a target to (aqa_runner.locators.Use).
type GeneratedUse = Literal["action"]

# The meaning of the one-locator targets each candidate is resolved as.
_CANDIDATE = "the element a use put a target to"

# The element's facts and its ancestors', nearest first, up to but not
# including <body>. Read in the page's own world, so they are the page's
# word: every candidate built from them is resolved before it is kept.
_FACTS = """(element) => {
    const facts = (node) => ({
        tag: node.localName,
        id: node.getAttribute("id"),
        classes: [...node.classList],
        name: node.getAttribute("name"),
        type: node.getAttribute("type"),
    });
    const ancestors = [];
    for (let node = element.parentElement; node; node = node.parentElement) {
        if (node === document.body || node === document.documentElement) break;
        ancestors.push(facts(node));
    }
    return {
        ...facts(element),
        placeholder: element.getAttribute("placeholder"),
        testid: element.getAttribute("data-testid"),
        labels: element.labels ? [...element.labels].map((label) => label.innerText) : [],
        ancestors,
    };
}"""


class _Node(TypedDict):
    tag: str
    id: str | None
    classes: list[str]
    name: str | None
    type: str | None


class _Element(_Node):
    placeholder: str | None
    testid: str | None
    labels: list[str]
    ancestors: list[_Node]


@dataclass(frozen=True)
class Seen:
    """The element a use put a target to, and the role and accessible name
    that its ref's line in the session's snapshot gives it. An element the
    snapshot gives no ref of its own, such as text inside a button, has
    neither."""

    element: ElementHandle
    role: str | None = None
    name: str | None = None


class LocatorError(LookupError):
    """No locator of the grammar finds the element, alone, for the use."""


def snapshot_elements(snapshot: str) -> dict[str, tuple[str, str | None]]:
    """Each element ref in a session's snapshot, in page order, with the role
    and the name, as written, that the snapshot gives the element."""
    elements: dict[str, tuple[str, str | None]] = {}
    for line in LINE.finditer(snapshot):
        key = line["key"]
        if key.startswith("'"):
            key = key[1:-1].replace("''", "'")
        own = ELEMENT_REF.search(key) if line["head"] else None
        described = None if own is None else _DESCRIBED.fullmatch(key, 0, own.start())
        if own is None or described is None:
            continue
        name = described["name"]
        elements[own[1]] = (
            described["role"],
            None if name is None else json.loads(name),
        )
    return elements


async def seen(session: BrowserSession, snapshot: str, ref: str) -> Seen:
    """The element `ref` names in the session's current snapshot, whose text
    is `snapshot`, with the role and name the snapshot gives it."""
    element = await session.locate(ref)
    role, name = snapshot_elements(snapshot).get(ref, (None, None))
    return Seen(element, role, name)


def _stable(token: str | None) -> bool:
    """Whether a css locator may use `token`: one plain identifier, not
    generated by a tool and not a state. A generated one has a prefix such as
    `css-`, or a part of five or more characters mixing letters and digits,
    such as the hash in `Button_root__x7Kd2`."""
    if token is None or not _TOKEN.fullmatch(token):
        return False
    if _GENERATED_PREFIX.match(token) or token in _STATE_CLASSES:
        return False
    return not any(
        len(part) >= 5 and re.search(r"[0-9]", part) and re.search(r"[A-Za-z]", part)
        for part in re.split(r"[-_]", token)
    )


def _structures(node: _Node) -> list[str]:
    """CSS for `node` alone, most particular first: its custom-element tag, a
    stable attribute, each stable class, then its tag. Never positional."""
    tag = node["tag"]
    if not _stable(tag):
        return []
    parts = [tag] if "-" in tag else []
    for attribute, value in (("name", node["name"]), ("type", node["type"])):
        if _stable(value):
            parts.append(f"{tag}[{attribute}={value}]")
    parts.extend(f"{tag}.{name}" for name in node["classes"] if _stable(name))
    parts.append(tag)
    return list(dict.fromkeys(parts))


def _scopes(element: _Element) -> Iterator[str]:
    """CSS for each ancestor that could pick out one place on the page,
    nearest first: its stable id, its custom-element tag, or its tag with one
    stable class. Never <html> or <body>, which every page has."""
    for node in element["ancestors"]:
        if _stable(node["id"]):
            yield f"#{node['id']}"
        for structure in _structures(node):
            if structure != node["tag"] or "-" in structure:
                yield structure


def _structural(element: _Element) -> Iterator[ByCss]:
    """Structural locators for the element, each alone and then under its
    nearest custom-element ancestor, such as `app-favorite-button button`."""
    custom = next(
        (
            node["tag"]
            for node in element["ancestors"]
            if "-" in node["tag"] and _stable(node["tag"])
        ),
        None,
    )
    for structure in _structures(element):
        yield ByCss(css=structure)
        if custom is not None:
            yield ByCss(css=f"{custom} {structure}")


async def _finds(page: Page, locator: Locator, used: Seen, use: GeneratedUse) -> bool:
    """Whether `locator`, alone, resolves for `use` to the element used."""
    found = await resolve(page, Target(semantic=_CANDIDATE, locators=(locator,)), use)
    if not isinstance(found, Resolved):
        return False
    try:
        same: bool = await page.evaluate(
            "([found, used]) => found === used", [found.element, used.element]
        )
        return same
    finally:
        await found.element.dispose()


async def _working(
    page: Page, locator: Locator, used: Seen, use: GeneratedUse, element: _Element
) -> Locator | None:
    """`locator` if it finds the element alone, else `locator` scoped under
    the nearest ancestor that makes it find the element, else None."""
    if await _finds(page, locator, used, use):
        return locator
    for scope in _scopes(element):
        scoped = locator.model_copy(update={"scope": ByCss(css=scope)})
        if await _finds(page, scoped, used, use):
            return scoped
    return None


def _candidates(used: Seen, element: _Element) -> list[list[Locator]]:
    """The grammar's kinds for an action, in its order, each with its
    candidates in order: role and name, label, placeholder, test ID, stable
    id, then structure (ADR-0025)."""
    role = used.role if used.role in _ROLES else None
    name = normalize(used.name or "") if role in _NAMED_ROLES else ""
    labels = [normalize(label) for label in element["labels"]]
    placeholder = (element["placeholder"] or "").strip()
    return [
        [ByRole.model_validate({"role": role, "name": name})] if name else [],
        [ByLabel(label=label) for label in labels if label],
        [ByPlaceholder(placeholder=placeholder)] if placeholder else [],
        [ByTestId(testid=element["testid"])] if element["testid"] else [],
        [ByCss(css=f"#{element['id']}")] if _stable(element["id"]) else [],
        list(_structural(element)),
    ]


async def generate(page: Page, used: Seen, use: GeneratedUse) -> tuple[Locator, ...]:
    """The locators that find the element `used` for `use`, one of each kind
    the grammar lists for it, in order, each resolved alone to that element
    on the page as it is now. Raises `LocatorError` when no locator does."""
    element = cast(_Element, await used.element.evaluate(_FACTS))
    found: list[Locator] = []
    for kind in _candidates(used, element):
        for candidate in kind:
            working = await _working(page, candidate, used, use, element)
            if working is not None:
                found.append(working)
                break
    if not found:
        raise LocatorError(
            f"no locator of the grammar finds the {element['tag']} element alone "
            f"for an {use}"
        )
    return tuple(found)
