"""Building a target's locators from the element a use put it to: the
compiler's half of ADR-0025's locator grammar (DATA_MODEL §7, Locators;
ADR-0025's 2026-10-02 amendment, "generating locators").

The caller says what the element is for and what each use is; this module
finds the locators, and `TargetUses` keeps one meaning's targets across its
uses. Every locator it returns was resolved alone, on the live page, to the
element the use put to it (a negative check's, where the element was seen,
then to nothing in its scope at the check). Which element a locator found is
judged in Playwright's utility world, which the page's scripts can't reach,
by a selector engine whoever opens the browser session registers first
(`register_identity_engine`), so a page can make the generator build fewer
or odder locators, but never one that finds another element."""

import json
import re
import secrets
import typing
from collections.abc import AsyncIterator, Awaitable, Callable, Iterator
from contextlib import asynccontextmanager, contextmanager
from dataclasses import dataclass, field
from typing import Annotated, Literal, TypedDict

from aqa_core.compiled import (
    AriaRole,
    ByCss,
    ByLabel,
    ByPlaceholder,
    ByRole,
    ByTestId,
    Locator,
    Target,
)
from aqa_core.text import normalize
from playwright.async_api import ElementHandle, Error, Page, Playwright
from pydantic import Field, StringConstraints, TypeAdapter, ValidationError

from aqa_runner.browser_session import ELEMENT_REF, LINE, BrowserSession
from aqa_runner.locators import Absent, Resolved, Use, resolve

# The key of an element's line in a snapshot, up to its ref: its role, its
# name as JSON if it has one, then attributes such as [level=1].
_DESCRIBED = re.compile(
    r'(?P<role>[a-z]+)(?: (?P<name>"(?:[^"\\\n]|\\.)*"))?(?: \[[^\]\n]*\])* '
)

# The roles whose accessible name a person reads as the control's label. Any
# other role is a container or a landmark, whose name, if it has one, is the
# text inside it, so a name never finds one (ADR-0025).
_NAMED_ROLES = frozenset(
    {
        "button",
        "checkbox",
        "combobox",
        "link",
        "menuitem",
        "menuitemcheckbox",
        "menuitemradio",
        "option",
        "radio",
        "searchbox",
        "slider",
        "spinbutton",
        "switch",
        "tab",
        "textbox",
        "treeitem",
    }
)

# The roles a role locator can take: Playwright's, less the ones that say an
# element has no role of its own.
_ROLES = frozenset(typing.get_args(AriaRole)) - {"generic", "none", "presentation"}

# A class, id, tag or attribute value that a css locator may use: one CSS
# identifier that needs no escaping, so it can't carry >>, a quote, a colon or
# a character Playwright trims.
_TOKEN = re.compile(r"[A-Za-z][A-Za-z0-9_-]*")
# Generated by a tool, not written by a person: CSS-in-JS prefixes and
# Angular's runtime classes (ng-untouched, ng-star-inserted).
_GENERATED_PREFIX = re.compile(r"(?:css|sc|jsx|emotion|svelte|ng)-")
# Classes that say what state an element is in, not what it is.
_STATE_CLASSES = frozenset(
    {
        "active",
        "checked",
        "collapsed",
        "disabled",
        "expanded",
        "focus",
        "hidden",
        "hover",
        "open",
        "selected",
        "show",
    }
)

# What one element may cost, whatever the page gives: the nearest ancestors
# and the first stable classes of each node that are tried, and the tries in
# all, each a resolution or a count.
_ANCESTORS_TRIED = 16
_CLASSES_TRIED = 16
_TRIES = 400

# A selector engine that holds the used element and says whether another is
# the same one. Registered as a content script, it runs in Playwright's
# utility world, an isolated world the page's scripts can't reach, and it
# reads no DOM state the page could move: `hold:<token>` keeps the element it
# is queried on, `is:<token>` finds that element only if it is the one kept,
# and `drop:<token>` forgets it.
# https://playwright.dev/python/docs/extensibility#custom-selector-engines
_IDENTITY = "aqa-identity"
_IDENTITY_ENGINE = """(() => {
    const held = new Map();
    const queryAll = (root, body) => {
        const cut = body.indexOf(":");
        const [verb, token] = [body.slice(0, cut), body.slice(cut + 1)];
        if (verb === "hold") held.set(token, root);
        if (verb === "drop") held.delete(token);
        return verb === "is" && held.get(token) === root ? [root] : [];
    };
    return { query: (root, body) => queryAll(root, body)[0] || null, queryAll };
})()"""

# What a use puts a target to (aqa_runner.locators.Use).
type GeneratedUse = Literal["action", "assertion"]

# The meaning of the one-locator targets each candidate is resolved as.
_CANDIDATE_MEANING = "the element a use put a target to"

# The element's facts and its nearest ancestors', up to but not including
# <body>. Read in the page's own world, so they are the page's word: every
# candidate built from them is resolved before it is kept.
_FACTS = f"""(element) => {{
    const facts = (node) => ({{
        tag: node.localName,
        id: node.getAttribute("id"),
        classes: [...node.classList],
        name: node.getAttribute("name"),
        type: node.getAttribute("type"),
    }});
    const ancestors = [];
    for (let node = element.parentElement; node; node = node.parentElement) {{
        if (node === document.body || node === document.documentElement) break;
        if (ancestors.length === {_ANCESTORS_TRIED}) break;
        ancestors.push(facts(node));
    }}
    return {{
        ...facts(element),
        placeholder: element.getAttribute("placeholder"),
        testid: element.getAttribute("data-testid"),
        labels: element.labels ? [...element.labels].map((label) => label.innerText) : [],
        ancestors,
    }};
}}"""

# The facts' shape, checked strictly, with bounded sizes: they come from the
# page's own world.
_TEXT_LENGTH = 1024
_Token = Annotated[str, StringConstraints(strict=True, max_length=256)]
_Text = Annotated[str, StringConstraints(strict=True, max_length=_TEXT_LENGTH)]


class _Node(TypedDict):
    tag: _Token
    id: _Text | None
    classes: Annotated[list[_Text], Field(max_length=256)]
    name: _Text | None
    type: _Text | None


class _Element(_Node):
    placeholder: _Text | None
    testid: _Text | None
    labels: Annotated[list[_Text], Field(max_length=64)]
    ancestors: Annotated[list[_Node], Field(max_length=_ANCESTORS_TRIED)]


_ELEMENT = TypeAdapter(_Element)


@dataclass(frozen=True)
class Seen:
    """The element a use put a target to, and the role and accessible name
    that its ref's line in the session's snapshot gives it. An element the
    snapshot gives no ref of its own, such as text inside a button, has
    neither."""

    element: ElementHandle
    role: str | None = None
    name: str | None = None


class LocatorError(LookupError):
    """No locator of the grammar finds the element, alone, for the use."""


def _name_as_written(name: str | None) -> str | None:
    """A snapshot name, decoded from JSON, or None for one that holds a lone
    surrogate, which no locator can carry. (Playwright 1.63's snapshot leaves
    out a name of thousands of characters itself.)"""
    if name is None:
        return None
    decoded: str = json.loads(name)
    try:
        decoded.encode()
    except UnicodeEncodeError:
        return None
    return decoded


def snapshot_elements(snapshot: str) -> dict[str, tuple[str, str | None]]:
    """Each element ref in a session's snapshot, in page order, with the role
    and the name, as written, that the snapshot gives the element."""
    elements: dict[str, tuple[str, str | None]] = {}
    for line in LINE.finditer(snapshot):
        key = line["key"]
        if key.startswith("'"):
            key = key[1:-1].replace("''", "'")
        own = ELEMENT_REF.search(key) if line["head"] else None
        described = None if own is None else _DESCRIBED.fullmatch(key, 0, own.start())
        if own is None or described is None:
            continue
        elements[own[1]] = (described["role"], _name_as_written(described["name"]))
    return elements


async def seen_element(session: BrowserSession, snapshot: str, ref: str) -> Seen:
    """The element `ref` names in the session's current snapshot, whose text
    is `snapshot`, with the role and name the snapshot gives it."""
    element = await session.locate(ref)
    role, name = snapshot_elements(snapshot).get(ref, (None, None))
    return Seen(element, role, name)


def _stable(token: str | None) -> bool:
    """Whether a css locator may use `token`: one plain identifier, not
    generated by a tool and not a state. A generated one has a prefix such as
    `css-`, or a part of five or more characters mixing letters and digits,
    such as the hash in `Button_root__x7Kd2`."""
    if token is None or not _TOKEN.fullmatch(token):
        return False
    if _GENERATED_PREFIX.match(token) or token in _STATE_CLASSES:
        return False
    return not any(
        len(part) >= 5 and re.search(r"[0-9]", part) and re.search(r"[A-Za-z]", part)
        for part in re.split(r"[-_]", token)
    )


def _structures(node: _Node) -> list[str]:
    """CSS for `node` alone, most particular first: its custom-element tag, a
    stable attribute, each of its first stable classes, then its tag. Never
    positional."""
    tag = node["tag"]
    if not _stable(tag):
        return []
    parts = [tag] if "-" in tag else []
    for attribute, value in (("name", node["name"]), ("type", node["type"])):
        if _stable(value):
            parts.append(f"{tag}[{attribute}={value}]")
    classes = [name for name in node["classes"] if _stable(name)]
    parts.extend(f"{tag}.{name}" for name in classes[:_CLASSES_TRIED])
    parts.append(tag)
    return list(dict.fromkeys(parts))


def _scopes(element: _Element) -> list[str]:
    """CSS for each ancestor that could pick out one place on the page,
    nearest first: its stable id, its custom-element tag, or its tag with a
    stable attribute or one stable class. Never <html> or <body>, which every
    page has."""
    scopes: list[str] = []
    for node in element["ancestors"]:
        ids = [f"#{node['id']}"] if _stable(node["id"]) else []
        # A bare tag names every element of its kind, unless it is a custom
        # element's.
        structures = [
            each for each in _structures(node) if each != node["tag"] or "-" in each
        ]
        scopes.extend(ids + structures)
    return list(dict.fromkeys(scopes))


def _structural(element: _Element) -> Iterator[ByCss]:
    """Structural locators for the element, each alone and then under its
    nearest custom-element ancestor, such as `app-favorite-button button`."""
    custom = next(
        (
            node["tag"]
            for node in element["ancestors"]
            if "-" in node["tag"] and _stable(node["tag"])
        ),
        None,
    )
    for structure in _structures(element):
        yield ByCss(css=structure)
        if custom is not None:
            yield ByCss(css=f"{custom} {structure}")


async def _unless_the_page_breaks(page: Page, check: Awaitable[bool]) -> bool:
    """`check`'s answer, or no when the page breaks it: Playwright's general
    error type, raised here when the page navigates away or drops an element
    mid-check, which is the page's doing. A closed page raises."""
    try:
        return await check
    except Error:
        if page.is_closed():
            raise
        return False


class _OutOfTriesError(Exception):
    """The trial spent its tries."""


async def _is_held(element: ElementHandle, token: str) -> bool:
    """Whether `element` is the one the identity engine holds for `token`:
    one query, in the utility world, that reads no DOM state."""
    same = await element.query_selector(f"{_IDENTITY}=is:{token}")
    if same is None:
        return False
    await same.dispose()
    return True


@dataclass
class _Trial:
    """Resolving candidates for one use of the element, which the identity
    engine holds as `token`, within a budget of tries."""

    page: Page
    use: Use
    token: str
    tries: int = _TRIES
    # Whether each scope finds one element on the page, counted once.
    counted: dict[str, bool] = field(default_factory=dict)

    def _spend(self) -> None:
        if self.tries == 0:
            raise _OutOfTriesError
        self.tries -= 1

    async def _found(self, locator: Locator) -> bool:
        target = Target(semantic=_CANDIDATE_MEANING, locators=(locator,))
        found = await resolve(self.page, target, self.use)
        if not isinstance(found, Resolved):
            return False
        try:
            return await _is_held(found.element, self.token)
        finally:
            await found.element.dispose()

    async def finds(self, locator: Locator) -> bool:
        """Whether `locator`, alone, resolves for the use to the element
        used."""
        self._spend()
        return await _unless_the_page_breaks(self.page, self._found(locator))

    async def _count_is_one(self, scope: str) -> bool:
        return await self.page.locator(f"css={scope}").count() == 1

    async def unique(self, scope: str) -> bool:
        """Whether `scope` finds one element on the page, counted once."""
        if scope not in self.counted:
            self._spend()
            self.counted[scope] = await _unless_the_page_breaks(
                self.page, self._count_is_one(scope)
            )
        return self.counted[scope]

    async def under(self, locator: Locator, scope: str) -> Locator | None:
        """`locator` scoped under `scope`, if the scope finds one element on
        the page and the locator finds the element inside it, else None."""
        if not await self.unique(scope):
            return None
        scoped = locator.model_copy(update={"scope": ByCss(css=scope)})
        return scoped if await self.finds(scoped) else None

    async def scoped_as_needed(
        self, locator: Locator, scopes: list[str]
    ) -> Locator | None:
        """`locator` if it finds the element alone, else `locator` scoped
        under the nearest scope, unique on the page, that makes it find the
        element, else None."""
        if await self.finds(locator):
            return locator
        for scope in scopes:
            if (scoped := await self.under(locator, scope)) is not None:
                return scoped
        return None


async def _facts(page: Page, element: ElementHandle) -> _Element:
    """The element's facts, as the page gives them. A page that breaks the
    reading or gives them in a form no element has gets no locator."""
    try:
        return _ELEMENT.validate_python(await element.evaluate(_FACTS), strict=True)
    except Error:
        # Playwright's general error type: here the element left the page or
        # the page's own scripts broke the reading. A closed page is not.
        if page.is_closed():
            raise
        raise LocatorError(
            "the element couldn't be read: it left the page, or the page's "
            "scripts broke the reading"
        ) from None
    except ValidationError:
        raise LocatorError("the page described the element as no element is") from None


async def register_identity_engine(playwright: Playwright) -> None:
    """Give `playwright` the selector engine the generator compares elements
    with. Call it once per Playwright instance, before the browser session
    opens: an engine reaches only the contexts created after it."""
    await playwright.selectors.register(
        _IDENTITY, script=_IDENTITY_ENGINE, content_script=True
    )


async def _held(page: Page, element: ElementHandle) -> str:
    """Have the identity engine hold `element`, and return its token."""
    token = secrets.token_hex(16)
    try:
        await element.query_selector(f"{_IDENTITY}=hold:{token}")
    except Error as error:
        if page.is_closed():
            raise
        if f'Unknown engine "{_IDENTITY}"' in str(error):
            raise RuntimeError(
                "the identity engine isn't registered: call "
                "register_identity_engine before the browser session opens"
            ) from None
        # Playwright's general error type, otherwise: here the element left
        # the page or its document, which is the page's doing.
        raise LocatorError("the element left the page before it was held") from None
    return token


async def _dropped(element: ElementHandle, token: str) -> bool:
    await element.query_selector(f"{_IDENTITY}=drop:{token}")
    return True


@asynccontextmanager
async def _holding(page: Page, element: ElementHandle) -> AsyncIterator[str]:
    """The identity engine holds `element` for the block, under the token
    given; then it forgets it, and a page that broke that keeps only an entry
    in a world it can't reach."""
    token = await _held(page, element)
    try:
        yield token
    finally:
        await _unless_the_page_breaks(page, _dropped(element, token))


def _role_and_name(used: Seen) -> tuple[str | None, str]:
    """The role a role locator may take, and the name only a control's name
    may carry, or "" (ADR-0025)."""
    role = used.role if used.role in _ROLES else None
    return role, normalize(used.name or "") if role in _NAMED_ROLES else ""


def _action_kinds(used: Seen, element: _Element) -> list[list[Locator]]:
    """The grammar's kinds for an action, in its order, each with its
    candidates in order: role and name, label, placeholder, test ID, stable
    id, then structure (ADR-0025)."""
    role, name = _role_and_name(used)
    labels = [normalize(label) for label in element["labels"]]
    placeholder = (element["placeholder"] or "").strip()
    return [
        [ByRole.model_validate({"role": role, "name": name})] if name else [],
        [ByLabel(label=label) for label in labels if label],
        [ByPlaceholder(placeholder=placeholder)] if placeholder else [],
        [ByTestId(testid=element["testid"])] if element["testid"] else [],
        [ByCss(css=f"#{element['id']}")] if _stable(element["id"]) else [],
        list(_structural(element)),
    ]


def _assertion_kinds(
    used: Seen, element: _Element, *, checks_text: bool
) -> list[list[Locator]]:
    """The grammar's kinds for an assertion, in its order: test ID, stable
    id, role, then structure (ADR-0025). A control's role carries its name
    only when the assertion checks no text: a name and the rendered text can
    share words without either accepting the other, as `aria-label="Save"`
    and "Save changes" do."""
    role, name = _role_and_name(used)
    by_role = (
        {"role": role, "name": name} if name and not checks_text else {"role": role}
    )
    return [
        [ByTestId(testid=element["testid"])] if element["testid"] else [],
        [ByCss(css=f"#{element['id']}")] if _stable(element["id"]) else [],
        [ByRole.model_validate(by_role)] if role is not None else [],
        list(_structural(element)),
    ]


# How each use needs a locator to find the element, for a message.
_HOW = {
    "action": "alone for an action",
    "assertion": "alone for an assertion",
    "negative_check": "under a scope for a negative check",
}


async def _placed(
    page: Page,
    used: Seen,
    use: Use,
    kinds_of: Callable[[_Element], list[list[Locator]]],
) -> list[list[Locator]]:
    """For each of the grammar's kinds, in order, its candidates where they
    find the element `used` for `use` (`_place`). Raises `LocatorError` when
    none does."""
    element = await _facts(page, used.element)
    kinds = kinds_of(element)
    placed: list[list[Locator]] = [[] for _ in kinds]
    async with _holding(page, used.element) as token:
        try:
            await _place(_Trial(page, use, token), kinds, _scopes(element), placed)
        except _OutOfTriesError:
            # Out of tries, the kinds found so far stand; with none, the
            # budget is the reason.
            if not any(placed):
                raise LocatorError(
                    f"no locator found the element within {_TRIES} tries"
                ) from None
    if not any(placed):
        what = f"the {element['tag']} element" if _stable(element["tag"]) else "it"
        raise LocatorError(f"no locator of the grammar finds {what} {_HOW[use]}")
    return placed


async def _place(
    trial: _Trial,
    kinds: list[list[Locator]],
    scopes: list[str],
    placed: list[list[Locator]],
) -> None:
    """Append to each kind's list in `placed` its candidates where they find
    the element. For an action or an assertion, that is the first candidate
    that does, scoped as needed. For a negative check, it is every candidate
    under every scope that makes it find the element, nearest first: the
    check runs on another page, where a scope unique here may not be."""
    for kind, found in zip(kinds, placed, strict=True):
        for candidate in kind:
            if trial.use == "negative_check":
                for scope in scopes:
                    if (scoped := await trial.under(candidate, scope)) is not None:
                        found.append(scoped)
            elif (
                working := await trial.scoped_as_needed(candidate, scopes)
            ) is not None:
                found.append(working)
                break


async def _generate(
    page: Page,
    used: Seen,
    use: GeneratedUse,
    kinds_of: Callable[[_Element], list[list[Locator]]],
) -> tuple[Locator, ...]:
    """The first candidate of each kind that finds the element for `use`,
    in order. Raises `LocatorError` when none does."""
    return tuple(
        found[0] for found in await _placed(page, used, use, kinds_of) if found
    )


async def generate_for_action(page: Page, used: Seen) -> tuple[Locator, ...]:
    """An action target's locators: one of each kind that finds the element
    `used`, in the grammar's order, each resolved alone, as an action, to
    that element on the page as it is now. Raises `LocatorError` when no
    locator does."""
    return await _generate(
        page, used, "action", lambda element: _action_kinds(used, element)
    )


async def generate_for_assertion(
    page: Page, used: Seen, *, checks_text: bool
) -> tuple[Locator, ...]:
    """An assertion target's locators: one of each kind that finds the
    element `used`, in the grammar's order, each resolved alone, as an
    assertion's target, to that element on the page as it is now.
    `checks_text` says whether any use of the target's meaning checks its
    text (`text_in_target`); then it is located by no name. `TargetUses`
    holds it for the meaning and passes it at every use.
    Raises `LocatorError` when no locator does."""
    return await _generate(
        page,
        used,
        "assertion",
        lambda element: _assertion_kinds(used, element, checks_text=checks_text),
    )


class TargetUses:
    """The targets one meaning needs across its uses, in the order the uses
    come (ADR-0025, "Targets used more than once"). A later use joins the
    current target only if every one of its locators holds at that use;
    otherwise it starts a new target, generated there. A locator is never
    dropped to keep a target whole."""

    def __init__(self, meaning: str, *, checks_text: bool) -> None:
        self.meaning = meaning
        self.checks_text = checks_text
        self._targets: list[Target] = []
        # Where a later negative check's element was seen: for each kind,
        # its candidates under every scope that found it there.
        self._seen: list[list[Locator]] = []

    @property
    def targets(self) -> tuple[Target, ...]:
        """The meaning's targets so far, in the order they were started."""
        return tuple(self._targets)

    async def add(self, page: Page, used: Seen, use: GeneratedUse) -> int:
        """The index in `targets` of the target this use of the element
        `used` gets."""
        with self._named():
            if not (self._targets and await self._holds(page, used, use)):
                if use == "action":
                    locators = await generate_for_action(page, used)
                else:
                    locators = await generate_for_assertion(
                        page, used, checks_text=self.checks_text
                    )
                self._targets.append(Target(semantic=self.meaning, locators=locators))
        return len(self._targets) - 1

    async def see_for_negative_check(self, page: Page, seen: Seen) -> None:
        """Generate, from the element `seen` on the page now, the locators a
        later negative check of the meaning starts its target from: an
        assertion's kinds, each scoped (ADR-0025's 2026-10-02 amendment)."""
        with self._named():
            self._seen = await _placed(
                page,
                seen,
                "negative_check",
                lambda element: _assertion_kinds(
                    seen, element, checks_text=self.checks_text
                ),
            )

    async def add_negative_check(self, page: Page) -> int:
        """The index in `targets` of the target a negative check of the
        meaning, on the page now, gets. A new one keeps, of each kind, the
        first locator seen (`see_for_negative_check`) whose scope is on the
        page with nothing visible in it."""
        with self._named():
            if not await self._holds_absent(page):
                if not self._seen:
                    raise LocatorError("it wasn't seen before its negative check")
                kept: list[Locator] = []
                for found in self._seen:
                    for locator in found:
                        if await _absent(page, locator):
                            kept.append(locator)
                            break
                if not kept:
                    raise LocatorError(
                        "no locator it was seen by finds its scope on the page "
                        "with nothing visible in it"
                    )
                self._targets.append(
                    Target(semantic=self.meaning, locators=tuple(kept))
                )
        return len(self._targets) - 1

    @contextmanager
    def _named(self) -> Iterator[None]:
        """A `LocatorError` raised in the block names the meaning."""
        try:
            yield
        except LocatorError as error:
            raise LocatorError(f"{self.meaning}: {error}") from None

    def _allows(self, locator: Locator, use: Use) -> bool:
        """Whether the grammar lets `locator` find the target for `use`: an
        assertion's target has no label or placeholder, and no name when the
        meaning's text is checked, and a negative check's is scoped
        (ADR-0025)."""
        if use == "action":
            return True
        named = isinstance(locator, ByRole) and locator.name is not None
        if isinstance(locator, ByLabel | ByPlaceholder) or (named and self.checks_text):
            return False
        return use == "assertion" or locator.scope is not None

    async def _holds(self, page: Page, used: Seen, use: GeneratedUse) -> bool:
        """Whether every locator of the current target is one the grammar
        allows for `use` and, alone, resolves for it to the element `used`."""
        locators = self._targets[-1].locators
        if not all(self._allows(locator, use) for locator in locators):
            return False
        async with _holding(page, used.element) as token:
            trial = _Trial(page, use, token)
            for locator in locators:
                if not await trial.finds(locator):
                    return False
        return True

    async def _holds_absent(self, page: Page) -> bool:
        """Whether every locator of the current target is one the grammar
        allows for a negative check and, alone, is absent from the page."""
        if not self._targets:
            return False
        locators = self._targets[-1].locators
        if not all(self._allows(locator, "negative_check") for locator in locators):
            return False
        for locator in locators:
            if not await _absent(page, locator):
                return False
        return True


async def _absent(page: Page, locator: Locator) -> bool:
    """Whether `locator`, alone, finds its scope on the page with nothing
    visible in it: a negative check's absence. A page that breaks the look
    gets no."""

    async def look() -> bool:
        target = Target(semantic=_CANDIDATE_MEANING, locators=(locator,))
        found = await resolve(page, target, "negative_check")
        if isinstance(found, Resolved):
            await found.element.dispose()
        return isinstance(found, Absent)

    return await _unless_the_page_breaks(page, look())
